require 'rspec'

require './lib/game_engine.rb'
require './lib/console_interface.rb'
require './lib/game_runner.rb'
require './lib/game_board.rb'
require './lib/algorithms/game_status_algorithm.rb'
require './lib/algorithms/computer_ai_algorithm.rb'
require './lib/internationalization/english_copy_provider.rb'
require './lib/internationalization/spanish_copy_provider.rb'
